sudo: true

dist: xenial

services: mysql

language: php

php:
    - 7.2
    - 7.4

env:
    global:
        - TMPDIR=/tmp
    matrix:
        # WP_VERSION=4.9.8 WP_MULTISITE=0 PREFER_LOWEST="" IMG_LIBS=0
        # WP_VERSION=4.9.8 WP_MULTISITE=1 PREFER_LOWEST="" IMG_LIBS=0
        - WP_VERSION=latest IMG_LIBS=1 WP_MULTISITE=0 PREFER_LOWEST="" 
        # WP_VERSION=latest WP_MULTISITE=1 PREFER_LOWEST="" IMG_LIBS=0

matrix:
    exclude:
    - php: 7.4
      env: WP_VERSION=4.9.8 WP_MULTISITE=0 PREFER_LOWEST="" IMG_LIBS=0
    - php: 7.4
      env: WP_VERSION=4.9.8 WP_MULTISITE=1 PREFER_LOWEST="" IMG_LIBS=0
    #include:
    #- php: 5.6.30
    #  env: WP_VERSION=4.9.8 IMG_LIBS=0 WP_MULTISITE=0 PREFER_LOWEST="--prefer-lowest --prefer-stable"

before_install:
    - sudo apt-get update
    - sudo apt-get install php7.2-gd
    #- echo "extension = gd.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini


before_script:
    - if [ "$IMG_LIBS" == 1 ]; then pear config-set preferred_state beta; pecl channel-update pecl.php.net; yes '' | pecl install imagick; fi
    - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
    - composer update $PREFER_LOWEST --dev --prefer-source
    - composer require satooshi/php-coveralls:1.0.*

script:
    - if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PHP_VERSION" == 7.2 ]; then mkdir -p build/logs; vendor/phpunit/phpunit/phpunit --coverage-clover build/logs/clover.xml -c phpunit.xml --verbose; else vendor/phpunit/phpunit/phpunit -c phpunit-nocover.xml --verbose; fi

after_script:
    - if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PHP_VERSION" == 7.2 ]; then php vendor/bin/coveralls -v; fi

after_success:
    - if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PHP_VERSION" == 7.2 ]; then coveralls; fi
    - bash <(curl -s https://codecov.io/bash)
