sudo: false

dist: xenial

services: mysql

language: php

addons:
  apt:
    packages:
      - libwebp-dev

php:
    - 7.4

env:
    global:
        - TMPDIR=/tmp
    matrix:
        - WP_VERSION=5.3.2 WP_MULTISITE=0
        - WP_VERSION=5.3.2 WP_MULTISITE=1
        - WP_VERSION=latest WP_MULTISITE=0 COVERAGE=1 IMG_LIBS=1 CODING_STYLE=1
        - WP_VERSION=latest WP_MULTISITE=1 COVERAGE=1 IMG_LIBS=1 STATIC_ANALYSIS=1
        
matrix:
    include:
    - php: 7.2
      env: WP_VERSION=5.3.2 WP_MULTISITE=0
    - php: 7.2
      env: WP_VERSION=latest WP_MULTISITE=0

before_install:
    # - phpenv config-add myconfig.ini --with-webp-dir
    - phpenv config-rm xdebug.ini
    - pecl install pcov

before_script:
    - if [ "$IMG_LIBS" == 1 ]; then pear config-set preferred_state beta; pecl channel-update pecl.php.net; yes '' | pecl install imagick; fi
    - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
    - composer update $PREFER_LOWEST --dev --prefer-source
    - vendor/bin/pcov clobber
    - if [ "$COVERAGE" == 1 ]; then composer require satooshi/php-coveralls:1.0.*; fi

script:
    - if [ "$CODING_STYLE" == 1 ]; then composer lint; fi
    - if [ "$COVERAGE" == 1 ]; then mkdir -p build/logs; vendor/phpunit/phpunit/phpunit --coverage-clover build/logs/clover.xml -c phpunit.xml --verbose; else vendor/phpunit/phpunit/phpunit -c phpunit-nocover.xml --verbose; fi
    - if [ "$STATIC_ANALYSIS" == 1 ]; then vendor/bin/phpstan analyze -l 1; fi

after_success:
    - if [ "$COVERAGE" == 1 ]; then bash <(curl -s https://codecov.io/bash) -Z; fi
    - if [ "$COVERAGE" == 1 ]; then vendor/bin/coveralls -v; fi
