os: linux

dist: xenial

services: mysql

language: php

addons:
  apt:
    packages:
      - libwebp-dev
      - python-software-properties
      - apt-transport-https
      - apt-utils

php:
  - 7.2

env:
  global:
    - TMPDIR=/tmp
    - COVERALLS_PARALLEL=true
  jobs:
    - WP_VERSION=4.9.8 WP_MULTISITE=0 
    - WP_VERSION=4.9.8 WP_MULTISITE=1
    - WP_VERSION=latest WP_MULTISITE=0
    - WP_VERSION=latest WP_MULTISITE=1

cache:
  directories:
    - "${HOME}/.composer/cache"

before_install:
  # phpenv config-add myconfig.ini --with-webp-dir
  - phpenv config-rm xdebug.ini
  # Install 
  - LC_ALL=C.UTF-8 sudo add-apt-repository -y ppa:ondrej/php
  - sudo apt-get update
  - sudo apt-get install -y "php${TRAVIS_PHP_VERSION}-cli" "php${TRAVIS_PHP_VERSION}-gd"

install:
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
  - composer update $PREFER_LOWEST --prefer-source

script:
  - php -v
  - which -a php
  - alias php=/usr/bin/php
  - php -v
  - php --rf imagewebp
