name: Timber Tests

on:
  push:
    branches:
      - '*'
  pull_request:
    types: [opened, synchronize, ready_for_review]

jobs:
  run:
    runs-on: ${{ matrix.operating-system }}

    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest]
        # php-versions: [ '8.0', '7.4', '7.3', '7.2', '7.1', '7.0', '5.6.20' ]
        php-versions: [ 7.4']
        # wp-versions: ['4.9', 'latest']
        wp-versions: ['latest']
        wp-multisite: ['1', '0']

    name: WP ${{ matrix.wp-versions }}${{ matrix.wp-multisite == 1 && ' (MS)' || '' }} with PHP ${{ matrix.php-versions }} on ${{ matrix.operating-system }}.

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        coverage: none  # XDebug can be enabled here 'coverage: xdebug'
        tools: composer:v1

    - name: Start mysql service
      run: sudo /etc/init.d/mysql start

    - name: Get composer cache directory
      id: composercache
      run: echo "::set-output name=dir::$(composer config cache-files-dir)"

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ${{ steps.composercache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
        restore-keys: ${{ runner.os }}-composer-

    - name: Install dependencies
      run: composer update --prefer-stable --prefer-source

    - name: Install tests
      run: bash bin/install-wp-tests.sh wordpress_test root root 127.0.0.1:3306 ${{ matrix.wp-versions }}

    - name: Test
      run: composer run test-unit
      env:
        WP_MULTISITE: ${{ matrix.multisite }}
